---
hpb-xdai:
  children:
    oracle:
      hosts:
        127.0.0.1:
          ansible_user: root
          ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: " "
          #syslog_server_port: "udp://127.0.0.1:514"
    monitor:
      hosts:
        127.0.0.1:
          ansible_user: root
          #syslog_server_port: "<protocol>://<ip>:<port>"
          #monitor_cron_schedule: "*/4 * * * *"
